Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/09/2024
Var
// Seção de Declarações das variáveis 
 msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 msg <- "Ola,Mundo!"
 Escreval("Mensagem: ", msg)
 Escreva("Me livrei da maldicao!")

Fimalgoritmo